SistemaCursoOnline/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaCursoOnline.Models
{
    public class Curso
    {
        [Key]
        public int IdCurso { get; set; }
        [Required]
        [StringLength(255, MinimumLength = 3)]

        [Display(Name = "Nome do Curso")]
        public string DescricaoCurso { get; set; }
        public bool Ativo { get; set; }
    }
}

SistemaCursoOnline/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaCursoOnline.Context;
using SistemaCursoOnline.Models;

namespace SistemaCursoOnline.Controllers
{
    public class CursoController : Controller
    {
        private Context.Context db = new Context.Context();

        // GET: Curso
        public ActionResult Index()
        {
            List<Curso> listaCurso = db.tbCurso.ToList();
            return View(listaCurso);
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.tbCurso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            //Criando novo Objeto Curso vazio
            Curso curso = new Curso();
            //Aplicando true para que o Ativo já vá com o check marcado
            curso.Ativo = true;
            return View(curso);
        }

        // POST: Curso/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCurso,DescricaoCurso,Ativo")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                curso.DescricaoCurso = "CR-" + curso.DescricaoCurso;
                db.tbCurso.Add(curso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(curso);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.tbCurso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCurso,DescricaoCurso,Ativo")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.tbCurso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Curso curso = db.tbCurso.Find(id);
            db.tbCurso.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaCursoOnline/Views/Curso/Create.cshtml
@model SistemaCursoOnline.Models.Curso

@{
    ViewBag.Title = "Adcicionar Curso";
}

<h2><strong>Adicionar Curso</strong></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Novo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoCurso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescricaoCurso, new { htmlAttributes = new { @class = "form-control", style = "width:300px;" } })
                @Html.ValidationMessageFor(model => model.DescricaoCurso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Ativo, new { htmlAttributers = new { style = "margin-top: 18px;" } })
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index", "Curso", new { @class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaCursoOnline/Views/Curso/Delete.cshtml
@model SistemaCursoOnline.Models.Curso

@{
    ViewBag.Title = "Remover Curso";
}

<h2><strong>Remover Curso</strong></h2>

<h3>Você tem certeza de que deseja remover este curso?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DescricaoCurso)
        </dt>

        <dd>
            @Html.EditorFor(model => model.DescricaoCurso, new { htmlAttributes = new { disabled = "true", @class = "form-control", style = "width:300px;" } })
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar à Lista", "Index", "Curso", new { @class="btn btn-default"})
        </div>
    }
</div>

SistemaCursoOnline/Views/Curso/Details.cshtml
@model SistemaCursoOnline.Models.Curso
@{
    ViewBag.Title = "Detalhes do Curso";
}

<h2><strong>Detalhes do Curso</strong></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DescricaoCurso)
        </dt>

        <dd>
            @Html.EditorFor(model => model.DescricaoCurso, new { htmlAttributes = new { disabled="true", @class = "form-control", style="width:300px;" } })
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.IdCurso }, new { @class="btn btn-info"}) |
    @Html.ActionLink("Voltar à lista", "Index", "Curso", new { @class = "btn btn-default" })
</p>

SistemaCursoOnline/Views/Curso/Edit.cshtml
@model SistemaCursoOnline.Models.Curso

@{
    ViewBag.Title = "Atualizar Curso";
}

<h2><strong>Atualizar Curso</strong></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCurso)

        <div class="form-group">
            @Html.LabelFor(model => model.DescricaoCurso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescricaoCurso, new { htmlAttributes = new { @class = "form-control", style = "width:300px;" } })
                @Html.ValidationMessageFor(model => model.DescricaoCurso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à Lista", "Index", "Curso", new { @class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaCursoOnline/Views/Curso/Index.cshtml
@model IEnumerable<SistemaCursoOnline.Models.Curso>

@{
    ViewBag.Title = "Cursos Cadastrados";
}

<h2>Cursos Cadastrados</h2>

<p>
    @Html.ActionLink("Adicionar Novo Curso", "Create", "Curso", new {@class="btn btn-link" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DescricaoCurso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DescricaoCurso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id = item.IdCurso },  htmlAttributes: new { @class="btn btn-success"}) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.IdCurso }, htmlAttributes: new { @class = "btn btn-info" }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.IdCurso }, htmlAttributes: new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>