SistemaCursoOnline/Models/Turma.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaCursoOnline.Models
{
    public class Turma
    {
        [Key]
        public int IdTurma { get; set; }

        [Display(Name = "Curso")]
        public int IdCurso { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Display(Name = "Nome da Turma")]
        public string DescricaoTurma { get; set; }
        [Range(0, 60)]

        [Display(Name = "Quantidade de Alunos")]
        public int QtdeAlunos { get; set; }

        [Required(ErrorMessage = "O campo Turno é obrigatório.")]
        public string Turno { get; set; }
        public bool Ativo { get; set; }

        public virtual string nomeCurso { get; set; }

    }
}

SistemaCursoOnline/Controllers/TurmaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaCursoOnline.Context;
using SistemaCursoOnline.Models;

namespace SistemaCursoOnline.Controllers
{
    public class TurmaController : Controller
    {
        private Context.Context db = new Context.Context();

        // GET: Turma
        public ActionResult Index()
        {
            List<Turma> listaTurmas = db.tbTurma.OrderBy(t => t.DescricaoTurma).ToList();
            List<Curso> listaCursos = db.tbCurso.ToList();
            ViewBag.ListaCursos = listaCursos;

            return View(listaTurmas);
        }

        // GET: Turma/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.tbTurma.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // GET: Turma/Create
        public ActionResult Create()
        {
            Turma turma = new Turma();
            turma.Ativo = true;
            ViewBag.ListaTurno = new List<string>() { "Matutino", "Vespertino", "Noturno" };

            List<Curso> listaCurso = db.tbCurso.ToList();
            ViewBag.ListaCurso = listaCurso;
            return View(turma);
        }

        // POST: Turma/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTurma,IdCurso,DescricaoTurma,QtdeAlunos,Turno,Ativo")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                db.tbTurma.Add(turma);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<Curso> listaCurso = db.tbCurso.ToList();
            ViewBag.ListaCurso = listaCurso;
            return View(turma);
        }

        // GET: Turma/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.tbTurma.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            List<Curso> listaCurso = db.tbCurso.ToList();
            ViewBag.ListaCurso = listaCurso;
            return View(turma);
        }

        // POST: Turma/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTurma,IdCurso,DescricaoTurma,QtdeAlunos,Turno,Ativo")] Turma turma)
        {
            List<Curso> listaCurso = db.tbCurso.ToList();
            List<Usuario> listaUsuarios = db.tbUsuario.Where(x => x.IdTurma == turma.IdTurma).ToList();

            if (ModelState.IsValid)
            {
                if (listaUsuarios.Count <= turma.QtdeAlunos)
                {
                    db.Entry(turma).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Erro! A quantidade de alunos já matriculados nesta turma é superior " +
                    "à quantidade de vagas que você deseja alterar");
            }
            ViewBag.ListaCurso = listaCurso;
            return View(turma);
        }

        // GET: Turma/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.tbTurma.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // POST: Turma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Turma turma = db.tbTurma.Find(id);
            db.tbTurma.Remove(turma);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaCursoOnline/Views/Turma/Create.cshtml
@model SistemaCursoOnline.Models.Turma

@{
    ViewBag.Title = "Adicionar Turma";
}

<h2><strong>Adicionar Turma</strong></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h4>Novo</h4>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DescricaoTurma, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DescricaoTurma, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DescricaoTurma, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.IdCurso, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdCurso", new SelectList(ViewBag.ListaCurso, "IdCurso", "DescricaoCurso"), "Selecione o Curso", new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.QtdeAlunos, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.QtdeAlunos, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.QtdeAlunos, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Turno, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Turno", new SelectList(ViewBag.ListaTurno),
                       new { htmlAttributes = new { @class = "form-control" }, @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Turno, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        
                            @Html.EditorFor(model => model.Ativo)
                            @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                        
                    </div>
                </div>
            </div>
        </div>
        <br />

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Adicionar" class="btn btn-success" />
                    </div>
                </div>
            </div>
            }

            <div>
                @Html.ActionLink("Voltar à Lista", "Index", "Turma", new { @class = "btn btn-default" })
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

SistemaCursoOnline/Views/Turma/Delete.cshtml
@model SistemaCursoOnline.Models.Turma

@{
    ViewBag.Title = "Remover Turma";
}

<h2><strong>Remover Turma</strong></h2>

<h4>Tem certeza de que deseja remover esta turma?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <div class="row">
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoTurma)

                </dt>

                <dd>
                    @Html.EditorFor(model => model.DescricaoTurma, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                </dd>
                <br />
            </div>


            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.QtdeAlunos)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.QtdeAlunos, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                    <br />
                </dd>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.Turno)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.Turno, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                </dd>
                <br />
            </div>

            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.Ativo)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.Ativo, new { htmlAttributes = new { disabled = "true" } })
                </dd>
            </div>
        </div>
        <br />
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar à Lista", "Index", "Turma", new { @class="btn btn-default"})
        </div>
    }
</div>

SistemaCursoOnline/Views/Turma/Details.cshtml
@model SistemaCursoOnline.Models.Turma

@{
    ViewBag.Title = "Detalhes da Turma";
}

<h2><strong>Detalhes da Turma</strong></h2>

<div>
    <hr />
    <div class="dl-horizontal">
        <div class="row">
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoTurma)

                </dt>

                <dd>
                    @Html.EditorFor(model => model.DescricaoTurma, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                </dd>
                <br />
            </div>

            
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.QtdeAlunos)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.QtdeAlunos, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                    <br />
                </dd>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.Turno)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.Turno, new { htmlAttributes = new { @class = "form-control", style = "width:300px;", disabled = "true" } })
                </dd>
                <br />
            </div>
            
            <div class="col-lg-6">
                <dt>
                    @Html.DisplayNameFor(model => model.Ativo)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.Ativo, new { htmlAttributes = new { disabled = "true" } })
                </dd>
            </div>
        </div>
        <br />
</div>
<p>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.IdTurma }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Voltar à Lista", "Index", "Turma", new { @class = "btn btn-default" })
</p>

SistemaCursoOnline/Views/Turma/Edit.cshtml
@model SistemaCursoOnline.Models.Turma

@{
    ViewBag.Title = "Atualizar Turma";
}

<h2><strong>Atualizar Turma</strong></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdTurma)

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.DescricaoTurma, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DescricaoTurma, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DescricaoTurma, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.IdCurso, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdCurso", new SelectList(ViewBag.ListaCurso, "IdCurso", "DescricaoCurso", Model.IdCurso), "Selecione o Curso", new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.QtdeAlunos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QtdeAlunos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QtdeAlunos, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Turno, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Turno, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Turno, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                        @Html.EditorFor(model => model.Ativo)
                        @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                    
                </div>
            </div>
        </div>
    </div>
    <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-success" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Voltar à Lista", "Index", "Turma", new { @class = "btn btn-default" })
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

SistemaCursoOnline/Views/Turma/Index.cshtml
@model IEnumerable<SistemaCursoOnline.Models.Turma>

@{
    ViewBag.Title = "Turmas Cadastradas";
}

<h2>Turmas Cadastradas</h2>

<p>
    @Html.ActionLink("Adicionar Nova Turma", "Create", "Turma", new { @class="btn btn-link"})
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.DescricaoTurma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdCurso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtdeAlunos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Turno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>

    <td>
        @Html.DisplayFor(modelItem => item.DescricaoTurma)
    </td>
    <td>
        @Html.DropDownList("IdCurso", new SelectList(ViewBag.ListaCursos, "IdCurso", "DescricaoCurso", item.IdCurso), new {  disabled="true" } )
      
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.QtdeAlunos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Turno)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ativo)
    </td>
    <td>
        @Html.ActionLink("Atualizar", "Edit", new { id = item.IdTurma }, new { @class="btn btn-success"}) |
        @Html.ActionLink("Detalhes", "Details", new { id = item.IdTurma }, new { @class = "btn btn-info" }) |
        @Html.ActionLink("Remover", "Delete", new { id = item.IdTurma }, new { @class = "btn btn-danger" })
    </td>
</tr>
    }

</table>